services:
  - type: web
    name: formula-madi
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      DEBUG: "False"
      SECRET_KEY: "django-insecure-change-this-later-1234567890"
      ALLOWED_HOSTS: "*"
